In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [14]:
"""
Data Types
Boolean
Integer(intc, intp, int8, int16, int32, int64)
Unsigned integer(uint8, uint16, uint32, uint64)
Float(16, 32, 64)
Complex(64, 128)
empty()
"""

arr = np.empty((3,2),dtype=int)
print(arr)

arr = np.zeros((3,2),dtype=float)
print(arr)


arr = np.ones((3,2),dtype=float)
print(arr)

[[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
a=(1,2,3,4,5)
b=np.asarray(a)
arr = np.array((1,2,3))
print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'tuple'>


In [23]:
a=np.array([[1,2,3],[6,7,8]])
print(a)


b = np.arange(1,10,2,int)
print(b)

[[1 2 3]
 [6 7 8]]
[1 3 5 7 9]


In [26]:
np.linspace(10, 20, num=4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [30]:
L1=np.array([1,2,3,4])
L2=np.array([1,2,3,4])
L1*L2

'''
string functions
add 
multiply
center
capitalize
title
lower
upper
split
split lines
strip
join
replace

'''





array([ 1,  4,  9, 16])

In [39]:
s1=np.char.add('string1','string2')
s1=np.array(['string1','s2'])
s2=np.array(["a",'b','c'])
np.char.multiply(s2,3)

s3='sd'
np.char.multiply(s3,3)

array('sdsdsd', dtype='<U6')

In [35]:
a = np.array(["a", "b", "c"])

np.char.multiply(a, 3)

array(['aaa', 'bbb', 'ccc'], dtype='<U3')

In [47]:
'''
Linear algebra Funtions
dot()
vdot()
inner()
matmul()
det()
solve()
inverse()

'''

a = [[1, 0], [0, 1]]

b = [[4, 1], [2, 2]]

np.dot(a, b)

a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)
print(np.append(a,b))

[1 2 3 4 5 6]


In [2]:
import math as m
import statistics as s

numbers=[1,2,3,4,5,6,6,7,8,9]
print(s.mean(numbers))
print(s.mode(numbers))
print(s.median(numbers))
print(s.stdev(numbers))
print(s.variance(numbers))

5.1
6
5.5
2.6012817353502227
6.766666666666667
